import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Meetsy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full dark`}>
      <body className="min-h-full flex flex-col">
        <Toaster position="top-center" />
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
